---
# first dump databases on engine and get connection variables
- name: dump databases
  include_role:
    name: ansible-role-ovirt-dump-db
  vars:
    ovirt_engine_db_dump_dwh: "{{ ovirt_engine_dwh_to_remote_db }}"
    ovirt_engine_db_dump_start_services: False
    ovirt_engine_db_dump_local_dir: "{{ playbook_dir }}/engine_dump"
  when:
    - ovirt_type == "engine"
    - not ovirt_engine_reset

- name: set global variables
  set_fact:
    backup_timestamp_main: "{{ lookup('pipe','date +%Y%m%d%H%M%S') }}"

- name: set engine variables
  set_fact:
    engine_ip: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
  when: hostvars[item]['ovirt_type'] == "engine"
  with_items: "{{ groups['all'] }}"

- name: set db variables
  set_fact:
    remote_db_ip: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
  when: hostvars[item]['ovirt_type'] == "remote_db"
  with_items: "{{ groups['all'] }}"

- name: get engine variables from file
  include_vars:
    file: "{{ playbook_dir }}/engine_dump/engine_variables.yml"
    name: ovirt_engine_db_dump_engine_db
  when:
    - ovirt_engine_to_remote_db
    - not ovirt_engine_reset

- name: get DWH variables from file
  include_vars:
    file: "{{ playbook_dir }}/engine_dump/dwh_variables.yml"
    name: ovirt_engine_db_dump_dwh_db
  when:
    - ovirt_engine_dwh_to_remote_db
    - not ovirt_engine_reset

# then prepare remote server - create databases and import data
- name: create databases and import data
  include_role:
    name: ansible-role-ovirt-remote-db
  vars:
    ovirt_engine_remote_db_port: "{{ ovirt_engine_db_dump_engine_db['ENGINE_DB_PORT'] }}"
    ovirt_engine_db_name: "{{ ovirt_engine_db_dump_engine_db['ENGINE_DB_DATABASE'] }}"
    ovirt_engine_db_user: "{{ ovirt_engine_db_dump_engine_db['ENGINE_DB_USER'] }}"
    ovirt_engine_db_password: "{{ ovirt_engine_db_dump_engine_db['ENGINE_DB_PASSWORD'] }}"
    ovirt_engine_remote_db: "{{ ovirt_engine_to_remote_db }}"
    ovirt_engine_dwh_remote_db: "{{ ovirt_engine_dwh_to_remote_db }}"
    ovirt_engine_dwh_db_name: "{{ ovirt_engine_db_dump_dwh_db['DWH_DB_DATABASE'] }}"
    ovirt_engine_dwh_db_user: "{{ ovirt_engine_db_dump_dwh_db['DWH_DB_USER'] }}"
    ovirt_engine_dwh_db_password: "{{ ovirt_engine_db_dump_dwh_db['DWH_DB_PASSWORD'] }}"
    ovirt_engine_remote_db_force: True
    ovirt_engine_remote_db_dump: "{{ playbook_dir }}/engine_dump/engine.tar"
    ovirt_engine_remote_db_dwh_dump: "{{ playbook_dir }}/engine_dump/dwh.tar"
    ovirt_engine_remote_db_access:
      - type: host
        address: "{{ engine_ip }}/32"
        method: md5
  when:
    - ovirt_type == "remote_db"
    - not ovirt_engine_reset

# set engine from local to remote db
- include_tasks: set-engine.yml
  when:
    - ovirt_type == "engine"
    - not ovirt_engine_reset

# check engine running
- name: check if ovirt-engine running (health page)
  uri:
    url: "http://{{ ansible_fqdn }}/ovirt-engine/services/health"
    status_code: 200
  register: ovirt_engine_status
  retries: 2
  delay: 5
  until: ovirt_engine_status is success
  ignore_errors: True
  when:
    - ovirt_type == "engine"
    - not ovirt_engine_reset

# engine is not running reset engine back to local
- name: engine not running - set back to local
  set_fact:
    ovirt_engine_drop_local_db: False
    ovirt_engine_reset: True
  when:
    - ovirt_type == "engine"
    - not ovirt_engine_reset
    - ovirt_engine_status is failed

# reset engine back to local db
- include_tasks: reset-engine.yml
  when:
    - ovirt_type == "engine"
    - ovirt_engine_reset

# clean
- name: remove dump files from local
  local_action:
    file path={{ playbook_dir }}/engine_dump state=absent
  when:
    - not ovirt_engine_reset

# drop databases
- include_tasks: remove-local-db.yml
  when:
    - ovirt_type == "engine"
    - ovirt_engine_drop_local_db
    - not ovirt_engine_reset
